site_name: MCP Gitignore Tool
site_author: Hsiang-Jen Li
theme:
  name: readthedocs
plugins:
  - search
nav:
  - Home: index.md
  - API Reference:
    - Endpoints: reference/endpoints.md
    - Data Models: reference/models.md
